import { Component } from '@angular/core';

declare var $:any;

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';
  dataToPass = 'yakko pitai';
  totalRows:number = 0;
  totalRows2:number = 0;
  updateCheckBox:any;
  expand:boolean = false;
  expandAction:string = "Expand";

  toggleExpand(){
    if(this.expand==true)
    {
      this.expand = false;
      this.expandAction = "Expand";
      let cols:any = this.columns;
      cols[4].breakpoints= 'xs,sm,md,lg';
      this.columns = Object.assign([], cols);
    }
    else if(this.expand==false)
    {
      this.expand = true;
      this.expandAction = "Collapse";
      let cols:any = this.columns;
      cols[4].breakpoints= 'xs,sm,md';
      this.columns = Object.assign([], cols);
    }
  }

  counterUpdate(event: any) {
    this.totalRows = event.totalRows;
  }

  SelectedRow(event:any)
  {
    console.log(event);
  }

  counterUpdate2(event: any) {
    this.totalRows2 = event.totalRows;
  }

  pageSizeChart = {lg:10,md:8,sm:6,xs:3};
  pageSize : number = 10;

  columns = [
    {
      name:'col1',
      displayName:'Col 1',
      canSort:true,
      canfilter:true,
      filterType:'Equal',
      dataType:'string',
    },
    {
      name:'col2',
      displayName:'Col 2',
      breakpoints:'xs',
      canSort:true,
      canfilter:true,
      filterType:'StartsWith',
      dataType:'string',
    },
    {
      name:'col3',
      displayName:'Col 3',
      breakpoints:'xs,sm',
      canSort:false,
      canfilter:true,
      filterType:'EndsWith',
      dataType:'string',
    },
    {
      name:'col4',
      displayName:'Col 4',
      breakpoints: 'xs,sm,md',
      canSort:true,
      canfilter:true,
      filterType:'Range',
      dataType:'number',
      roundProgressbar:true,
    },
    {
      name:'col5',
      displayName:'Date of Birth',
      breakpoints: 'xs,sm,md,lg',
      canSort:true,
      canfilter:true,
      filterType:'Range',
      dataType:'date',
    }
  ];

  rows = [
    {col1:'Vaibhav', col2:'Durhaya', col3:'Bhopal',col4:32,col5:"1984/05/04"},
    {col1:'Richa', col2:'Saxena', col3:'Lucknow',col4:30,col5:"1984/05/05"},
    {col1:'Ajay', col2:'Gupta', col3:'Allahabad',col4:33,col5:"1984/05/06"},
    {col1:'Tushar', col2:'Bobade', col3:'Mumbai',col4:28,col5:"1984/05/07"},
    {col1:'Limbaji', col2:'Rathod', col3:'Rajasthan',col4:30,col5:"1984/05/08"},
    {col1:'Sonali', col2:'Katkar', col3:'Mumbai',col4:26,col5:"1984/05/09"},
    {col1:'Kiran', col2:'Yadav', col3:'Nashik',col4:31,col5:"1984/05/10"},
    {col1:'Bhushan', col2:'Patil', col3:'Nashik',col4:26,col5:"1984/05/11"},
    {col1:'Vaibhav', col2:'Durhaya', col3:'Bhopal',col4:32,col5:"1984/05/12"},
    {col1:'Richa', col2:'Saxena', col3:'Lucknow',col4:30,col5:"1984/05/13"},
    {col1:'Ajay', col2:'Gupta', col3:'Allahabad',col4:33,col5:"1984/05/14"},
    {col1:'Tushar', col2:'Bobade', col3:'Mumbai',col4:28,col5:"1984/05/15"},
    {col1:'Limbaji', col2:'Rathod', col3:'Rajasthan',col4:30,col5:"1984/05/16"},
    {col1:'Sonali', col2:'Katkar', col3:'Mumbai',col4:26,col5:"1984/05/17"},
    {col1:'Kiran', col2:'Yadav', col3:'Nashik',col4:31,col5:"1984/05/18"},
    {col1:'Bhushan', col2:'Patil', col3:'Nashik',col4:26},
    {col1:'Vaibhav', col2:'Durhaya', col3:'Bhopal',col4:32},
    {col1:'Richa', col2:'Saxena', col3:'Lucknow',col4:30},
    {col1:'Ajay', col2:'Gupta', col3:'Allahabad',col4:33},
    {col1:'Tushar', col2:'Bobade', col3:'Mumbai',col4:28},
    {col1:'Limbaji', col2:'Rathod', col3:'Rajasthan',col4:30},
    {col1:'Sonali', col2:'Katkar', col3:'Mumbai',col4:26},
    {col1:'Kiran', col2:'Yadav', col3:'Nashik',col4:31},
    {col1:'Bhushan', col2:'Patil', col3:'Nashik',col4:26},
    {col1:'Vaibhav', col2:'Durhaya', col3:'Bhopal',col4:32},
    {col1:'Richa', col2:'Saxena', col3:'Lucknow',col4:30},
    {col1:'Ajay', col2:'Gupta', col3:'Allahabad',col4:33},
    {col1:'Tushar', col2:'Bobade', col3:'Mumbai',col4:28},
    {col1:'Limbaji', col2:'Rathod', col3:'Rajasthan',col4:30},
    {col1:'Sonali', col2:'Katkar', col3:'Mumbai',col4:26},
    {col1:'Kiran', col2:'Yadav', col3:'Nashik',col4:31},
    {col1:'Bhushan', col2:'Patil', col3:'Nashik',col4:26},
    {col1:'Vaibhav', col2:'Durhaya', col3:'Bhopal',col4:32},
    {col1:'Richa', col2:'Saxena', col3:'Lucknow',col4:30},
    {col1:'Ajay', col2:'Gupta', col3:'Allahabad',col4:33},
    {col1:'Tushar', col2:'Bobade', col3:'Mumbai',col4:28},
    {col1:'Limbaji', col2:'Rathod', col3:'Rajasthan',col4:30},
    {col1:'Sonali', col2:'Katkar', col3:'Mumbai',col4:26},
    {col1:'Kiran', col2:'Yadav', col3:'Nashik',col4:31},
    {col1:'Bhushan', col2:'Patil', col3:'Nashik',col4:26},
    {col1:'Vaibhav', col2:'Durhaya', col3:'Bhopal',col4:32},
    {col1:'Richa', col2:'Saxena', col3:'Lucknow',col4:30},
    {col1:'Ajay', col2:'Gupta', col3:'Allahabad',col4:33},
    {col1:'Tushar', col2:'Bobade', col3:'Mumbai',col4:28},
    {col1:'Limbaji', col2:'Rathod', col3:'Rajasthan',col4:30},
    {col1:'Sonali', col2:'Katkar', col3:'Mumbai',col4:26},
    {col1:'Kiran', col2:'Yadav', col3:'Nashik',col4:31},
    {col1:'Bhushan', col2:'Patil', col3:'Nashik',col4:26},
    {col1:'Vaibhav', col2:'Durhaya', col3:'Bhopal',col4:32},
    {col1:'Richa', col2:'Saxena', col3:'Lucknow',col4:30},
    {col1:'Ajay', col2:'Gupta', col3:'Allahabad',col4:33},
    {col1:'Tushar', col2:'Bobade', col3:'Mumbai',col4:28},
    {col1:'Limbaji', col2:'Rathod', col3:'Rajasthan',col4:30},
    {col1:'Sonali', col2:'Katkar', col3:'Mumbai',col4:26},
    {col1:'Kiran', col2:'Yadav', col3:'Nashik',col4:31},
    {col1:'Bhushan', col2:'Patil', col3:'Nashik',col4:26},
    {col1:'Vaibhav', col2:'Durhaya', col3:'Bhopal',col4:32},
    {col1:'Richa', col2:'Saxena', col3:'Lucknow',col4:30},
    {col1:'Ajay', col2:'Gupta', col3:'Allahabad',col4:33},
    {col1:'Tushar', col2:'Bobade', col3:'Mumbai',col4:28},
    {col1:'Limbaji', col2:'Rathod', col3:'Rajasthan',col4:30},
    {col1:'Sonali', col2:'Katkar', col3:'Mumbai',col4:26},
    {col1:'Kiran', col2:'Yadav', col3:'Nashik',col4:31},
    {col1:'Bhushan', col2:'Patil', col3:'Nashik',col4:26},
    {col1:'Vaibhav', col2:'Durhaya', col3:'Bhopal',col4:32},
    {col1:'Richa', col2:'Saxena', col3:'Lucknow',col4:30},
    {col1:'Ajay', col2:'Gupta', col3:'Allahabad',col4:33},
    {col1:'Tushar', col2:'Bobade', col3:'Mumbai',col4:28},
    {col1:'Limbaji', col2:'Rathod', col3:'Rajasthan',col4:30},
    {col1:'Sonali', col2:'Katkar', col3:'Mumbai',col4:26},
    {col1:'Kiran', col2:'Yadav', col3:'Nashik',col4:31},
    {col1:'Bhushan', col2:'Patil', col3:'Nashik',col4:26},
    {col1:'Vaibhav', col2:'Durhaya', col3:'Bhopal',col4:32},
    {col1:'Richa', col2:'Saxena', col3:'Lucknow',col4:30},
    {col1:'Ajay', col2:'Gupta', col3:'Allahabad',col4:33},
    {col1:'Tushar', col2:'Bobade', col3:'Mumbai',col4:28},
    {col1:'Limbaji', col2:'Rathod', col3:'Rajasthan',col4:30},
    {col1:'Sonali', col2:'Katkar', col3:'Mumbai',col4:26},
    {col1:'Kiran', col2:'Yadav', col3:'Nashik',col4:31},
    {col1:'Bhushan', col2:'Patil', col3:'Nashik',col4:26},
    {col1:'Vaibhav', col2:'Durhaya', col3:'Bhopal',col4:32},
    {col1:'Richa', col2:'Saxena', col3:'Lucknow',col4:30},
    {col1:'Ajay', col2:'Gupta', col3:'Allahabad',col4:33},
    {col1:'Tushar', col2:'Bobade', col3:'Mumbai',col4:28},
    {col1:'Limbaji', col2:'Rathod', col3:'Rajasthan',col4:30},
    {col1:'Sonali', col2:'Katkar', col3:'Mumbai',col4:26},
    {col1:'Kiran', col2:'Yadav', col3:'Nashik',col4:31},
    {col1:'Bhushan', col2:'Patil', col3:'Nashik',col4:26},
    {col1:'Vaibhav', col2:'Durhaya', col3:'Bhopal',col4:32},
    {col1:'Richa', col2:'Saxena', col3:'Lucknow',col4:30},
    {col1:'Ajay', col2:'Gupta', col3:'Allahabad',col4:33},
    {col1:'Tushar', col2:'Bobade', col3:'Mumbai',col4:28},
    {col1:'Limbaji', col2:'Rathod', col3:'Rajasthan',col4:30},
    {col1:'Sonali', col2:'Katkar', col3:'Mumbai',col4:26},
    {col1:'Kiran', col2:'Yadav', col3:'Nashik',col4:31},
    {col1:'Bhushan', col2:'Patil', col3:'Nashik',col4:26},
    {col1:'Vaibhav', col2:'Durhaya', col3:'Bhopal',col4:32},
    {col1:'Richa', col2:'Saxena', col3:'Lucknow',col4:30},
    {col1:'Ajay', col2:'Gupta', col3:'Allahabad',col4:33},
    {col1:'Tushar', col2:'Bobade', col3:'Mumbai',col4:28},
    {col1:'Limbaji', col2:'Rathod', col3:'Rajasthan',col4:30},
    {col1:'Sonali', col2:'Katkar', col3:'Mumbai',col4:26},
    {col1:'Kiran', col2:'Yadav', col3:'Nashik',col4:31},
    {col1:'Bhushan', col2:'Patil', col3:'Nashik',col4:26},
    {col1:'Vaibhav', col2:'Durhaya', col3:'Bhopal',col4:32},
    {col1:'Richa', col2:'Saxena', col3:'Lucknow',col4:30},
    {col1:'Ajay', col2:'Gupta', col3:'Allahabad',col4:33},
    {col1:'Tushar', col2:'Bobade', col3:'Mumbai',col4:28},
    {col1:'Limbaji', col2:'Rathod', col3:'Rajasthan',col4:30},
    {col1:'Sonali', col2:'Katkar', col3:'Mumbai',col4:26},
    {col1:'Kiran', col2:'Yadav', col3:'Nashik',col4:31},
    {col1:'Bhushan', col2:'Patil', col3:'Nashik',col4:26},
    {col1:'Vaibhav', col2:'Durhaya', col3:'Bhopal',col4:32},
    {col1:'Richa', col2:'Saxena', col3:'Lucknow',col4:30},
    {col1:'Ajay', col2:'Gupta', col3:'Allahabad',col4:33},
    {col1:'Tushar', col2:'Bobade', col3:'Mumbai',col4:28},
    {col1:'Limbaji', col2:'Rathod', col3:'Rajasthan',col4:30},
    {col1:'Sonali', col2:'Katkar', col3:'Mumbai',col4:26},
    {col1:'Kiran', col2:'Yadav', col3:'Nashik',col4:31},
    {col1:'Bhushan', col2:'Patil', col3:'Nashik',col4:26},
    {col1:'Vaibhav', col2:'Durhaya', col3:'Bhopal',col4:32},
    {col1:'Richa', col2:'Saxena', col3:'Lucknow',col4:30},
    {col1:'Ajay', col2:'Gupta', col3:'Allahabad',col4:33},
    {col1:'Tushar', col2:'Bobade', col3:'Mumbai',col4:28},
    {col1:'Limbaji', col2:'Rathod', col3:'Rajasthan',col4:30},
    {col1:'Sonali', col2:'Katkar', col3:'Mumbai',col4:26},
    {col1:'Kiran', col2:'Yadav', col3:'Nashik',col4:31},
    {col1:'Bhushan', col2:'Patil', col3:'Nashik',col4:26},
    {col1:'Vaibhav', col2:'Durhaya', col3:'Bhopal',col4:32},
    {col1:'Richa', col2:'Saxena', col3:'Lucknow',col4:30},
    {col1:'Ajay', col2:'Gupta', col3:'Allahabad',col4:33},
    {col1:'Tushar', col2:'Bobade', col3:'Mumbai',col4:28},
    {col1:'Limbaji', col2:'Rathod', col3:'Rajasthan',col4:30},
    {col1:'Sonali', col2:'Katkar', col3:'Mumbai',col4:26},
    {col1:'Kiran', col2:'Yadav', col3:'Nashik',col4:31},
    {col1:'Bhushan', col2:'Patil', col3:'Nashik',col4:26},
    {col1:'Vaibhav', col2:'Durhaya', col3:'Bhopal',col4:32},
    {col1:'Richa', col2:'Saxena', col3:'Lucknow',col4:30},
    {col1:'Ajay', col2:'Gupta', col3:'Allahabad',col4:33},
    {col1:'Tushar', col2:'Bobade', col3:'Mumbai',col4:28},
    {col1:'Limbaji', col2:'Rathod', col3:'Rajasthan',col4:30},
    {col1:'Sonali', col2:'Katkar', col3:'Mumbai',col4:26},
    {col1:'Kiran', col2:'Yadav', col3:'Nashik',col4:31},
    {col1:'Bhushan', col2:'Patil', col3:'Nashik',col4:26},
    {col1:'Vaibhav', col2:'Durhaya', col3:'Bhopal',col4:32},
    {col1:'Richa', col2:'Saxena', col3:'Lucknow',col4:30},
    {col1:'Ajay', col2:'Gupta', col3:'Allahabad',col4:33},
    {col1:'Tushar', col2:'Bobade', col3:'Mumbai',col4:28},
    {col1:'Limbaji', col2:'Rathod', col3:'Rajasthan',col4:30},
    {col1:'Sonali', col2:'Katkar', col3:'Mumbai',col4:26},
    {col1:'Kiran', col2:'Yadav', col3:'Nashik',col4:31},
    {col1:'Bhushan', col2:'Patil', col3:'Nashik',col4:26},
    {col1:'Vaibhav', col2:'Durhaya', col3:'Bhopal',col4:32},
    {col1:'Richa', col2:'Saxena', col3:'Lucknow',col4:30},
    {col1:'Ajay', col2:'Gupta', col3:'Allahabad',col4:33},
    {col1:'Tushar', col2:'Bobade', col3:'Mumbai',col4:28},
    {col1:'Limbaji', col2:'Rathod', col3:'Rajasthan',col4:30},
    {col1:'Sonali', col2:'Katkar', col3:'Mumbai',col4:26},
    {col1:'Kiran', col2:'Yadav', col3:'Nashik',col4:31},
    {col1:'Bhushan', col2:'Patil', col3:'Nashik',col4:26},
    {col1:'Vaibhav', col2:'Durhaya', col3:'Bhopal',col4:32},
    {col1:'Richa', col2:'Saxena', col3:'Lucknow',col4:30},
    {col1:'Ajay', col2:'Gupta', col3:'Allahabad',col4:33},
    {col1:'Tushar', col2:'Bobade', col3:'Mumbai',col4:28},
    {col1:'Limbaji', col2:'Rathod', col3:'Rajasthan',col4:30},
    {col1:'Sonali', col2:'Katkar', col3:'Mumbai',col4:26},
    {col1:'Kiran', col2:'Yadav', col3:'Nashik',col4:31},
    {col1:'Bhushan', col2:'Patil', col3:'Nashik',col4:26},
    {col1:'Vaibhav', col2:'Durhaya', col3:'Bhopal',col4:32},
    {col1:'Richa', col2:'Saxena', col3:'Lucknow',col4:30},
    {col1:'Ajay', col2:'Gupta', col3:'Allahabad',col4:33},
    {col1:'Tushar', col2:'Bobade', col3:'Mumbai',col4:28},
    {col1:'Limbaji', col2:'Rathod', col3:'Rajasthan',col4:30},
    {col1:'Sonali', col2:'Katkar', col3:'Mumbai',col4:26},
    {col1:'Kiran', col2:'Yadav', col3:'Nashik',col4:31},
    {col1:'Bhushan', col2:'Patil', col3:'Nashik',col4:26},
    {col1:'Vaibhav', col2:'Durhaya', col3:'Bhopal',col4:32},
    {col1:'Richa', col2:'Saxena', col3:'Lucknow',col4:30},
    {col1:'Ajay', col2:'Gupta', col3:'Allahabad',col4:33},
    {col1:'Tushar', col2:'Bobade', col3:'Mumbai',col4:28},
    {col1:'Limbaji', col2:'Rathod', col3:'Rajasthan',col4:30},
    {col1:'Sonali', col2:'Katkar', col3:'Mumbai',col4:26},
    {col1:'Kiran', col2:'Yadav', col3:'Nashik',col4:31},
    {col1:'Bhushan', col2:'Patil', col3:'Nashik',col4:26},
    {col1:'Vaibhav', col2:'Durhaya', col3:'Bhopal',col4:32},
    {col1:'Richa', col2:'Saxena', col3:'Lucknow',col4:30},
    {col1:'Ajay', col2:'Gupta', col3:'Allahabad',col4:33},
    {col1:'Tushar', col2:'Bobade', col3:'Mumbai',col4:28},
    {col1:'Limbaji', col2:'Rathod', col3:'Rajasthan',col4:30},
    {col1:'Sonali', col2:'Katkar', col3:'Mumbai',col4:26},
    {col1:'Kiran', col2:'Yadav', col3:'Nashik',col4:31},
    {col1:'Bhushan', col2:'Patil', col3:'Nashik',col4:26},
    {col1:'Vaibhav', col2:'Durhaya', col3:'Bhopal',col4:32},
    {col1:'Richa', col2:'Saxena', col3:'Lucknow',col4:30},
    {col1:'Ajay', col2:'Gupta', col3:'Allahabad',col4:33},
    {col1:'Tushar', col2:'Bobade', col3:'Mumbai',col4:28},
    {col1:'Limbaji', col2:'Rathod', col3:'Rajasthan',col4:30},
    {col1:'Sonali', col2:'Katkar', col3:'Mumbai',col4:26},
    {col1:'Kiran', col2:'Yadav', col3:'Nashik',col4:31},
    {col1:'Bhushan', col2:'Patil', col3:'Nashik',col4:26},
    {col1:'Vaibhav', col2:'Durhaya', col3:'Bhopal',col4:32},
    {col1:'Richa', col2:'Saxena', col3:'Lucknow',col4:30},
    {col1:'Ajay', col2:'Gupta', col3:'Allahabad',col4:33},
    {col1:'Tushar', col2:'Bobade', col3:'Mumbai',col4:28},
    {col1:'Limbaji', col2:'Rathod', col3:'Rajasthan',col4:30},
    {col1:'Sonali', col2:'Katkar', col3:'Mumbai',col4:26},
    {col1:'Kiran', col2:'Yadav', col3:'Nashik',col4:31},
    {col1:'Bhushan', col2:'Patil', col3:'Nashik',col4:26},
    {col1:'Vaibhav', col2:'Durhaya', col3:'Bhopal',col4:32},
    {col1:'Richa', col2:'Saxena', col3:'Lucknow',col4:30},
    {col1:'Ajay', col2:'Gupta', col3:'Allahabad',col4:33},
    {col1:'Tushar', col2:'Bobade', col3:'Mumbai',col4:28},
    {col1:'Limbaji', col2:'Rathod', col3:'Rajasthan',col4:30},
    {col1:'Sonali', col2:'Katkar', col3:'Mumbai',col4:26},
    {col1:'Kiran', col2:'Yadav', col3:'Nashik',col4:31},
    {col1:'Bhushan', col2:'Patil', col3:'Nashik',col4:26},
    {col1:'Vaibhav', col2:'Durhaya', col3:'Bhopal',col4:32},
    {col1:'Richa', col2:'Saxena', col3:'Lucknow',col4:30},
    {col1:'Ajay', col2:'Gupta', col3:'Allahabad',col4:33},
    {col1:'Tushar', col2:'Bobade', col3:'Mumbai',col4:28},
    {col1:'Limbaji', col2:'Rathod', col3:'Rajasthan',col4:30},
    {col1:'Sonali', col2:'Katkar', col3:'Mumbai',col4:26},
    {col1:'Kiran', col2:'Yadav', col3:'Nashik',col4:31},
    {col1:'Bhushan', col2:'Patil', col3:'Nashik',col4:26},
    {col1:'Vaibhav', col2:'Durhaya', col3:'Bhopal',col4:32},
    {col1:'Richa', col2:'Saxena', col3:'Lucknow',col4:30},
    {col1:'Ajay', col2:'Gupta', col3:'Allahabad',col4:33},
    {col1:'Tushar', col2:'Bobade', col3:'Mumbai',col4:28},
    {col1:'Limbaji', col2:'Rathod', col3:'Rajasthan',col4:30},
    {col1:'Sonali', col2:'Katkar', col3:'Mumbai',col4:26},
    {col1:'Kiran', col2:'Yadav', col3:'Nashik',col4:31},
    {col1:'Bhushan', col2:'Patil', col3:'Nashik',col4:26},
    {col1:'Vaibhav', col2:'Durhaya', col3:'Bhopal',col4:32},
    {col1:'Richa', col2:'Saxena', col3:'Lucknow',col4:30},
    {col1:'Ajay', col2:'Gupta', col3:'Allahabad',col4:33},
    {col1:'Tushar', col2:'Bobade', col3:'Mumbai',col4:28},
    {col1:'Limbaji', col2:'Rathod', col3:'Rajasthan',col4:30},
    {col1:'Sonali', col2:'Katkar', col3:'Mumbai',col4:26},
    {col1:'Kiran', col2:'Yadav', col3:'Nashik',col4:31},
    {col1:'Bhushan', col2:'Patil', col3:'Nashik',col4:26},
    {col1:'Vaibhav', col2:'Durhaya', col3:'Bhopal',col4:32},
    {col1:'Richa', col2:'Saxena', col3:'Lucknow',col4:30},
    {col1:'Ajay', col2:'Gupta', col3:'Allahabad',col4:33},
    {col1:'Tushar', col2:'Bobade', col3:'Mumbai',col4:28},
    {col1:'Limbaji', col2:'Rathod', col3:'Rajasthan',col4:30},
    {col1:'Sonali', col2:'Katkar', col3:'Mumbai',col4:26},
    {col1:'Kiran', col2:'Yadav', col3:'Nashik',col4:31},
    {col1:'Bhushan', col2:'Patil', col3:'Nashik',col4:26},
    {col1:'Vaibhav', col2:'Durhaya', col3:'Bhopal',col4:32},
    {col1:'Richa', col2:'Saxena', col3:'Lucknow',col4:30},
    {col1:'Ajay', col2:'Gupta', col3:'Allahabad',col4:33},
    {col1:'Tushar', col2:'Bobade', col3:'Mumbai',col4:28},
    {col1:'Limbaji', col2:'Rathod', col3:'Rajasthan',col4:30},
    {col1:'Sonali', col2:'Katkar', col3:'Mumbai',col4:26},
    {col1:'Kiran', col2:'Yadav', col3:'Nashik',col4:31},
    {col1:'Bhushan', col2:'Patil', col3:'Nashik',col4:26},
    {col1:'Vaibhav', col2:'Durhaya', col3:'Bhopal',col4:32},
    {col1:'Richa', col2:'Saxena', col3:'Lucknow',col4:30},
    {col1:'Ajay', col2:'Gupta', col3:'Allahabad',col4:33},
    {col1:'Tushar', col2:'Bobade', col3:'Mumbai',col4:28},
    {col1:'Limbaji', col2:'Rathod', col3:'Rajasthan',col4:30},
    {col1:'Sonali', col2:'Katkar', col3:'Mumbai',col4:26},
    {col1:'Kiran', col2:'Yadav', col3:'Nashik',col4:31},
    {col1:'Bhushan', col2:'Patil', col3:'Nashik',col4:26},
    {col1:'Vaibhav', col2:'Durhaya', col3:'Bhopal',col4:32},
    {col1:'Richa', col2:'Saxena', col3:'Lucknow',col4:30},
    {col1:'Ajay', col2:'Gupta', col3:'Allahabad',col4:33},
    {col1:'Tushar', col2:'Bobade', col3:'Mumbai',col4:28},
    {col1:'Limbaji', col2:'Rathod', col3:'Rajasthan',col4:30},
    {col1:'Sonali', col2:'Katkar', col3:'Mumbai',col4:26},
    {col1:'Kiran', col2:'Yadav', col3:'Nashik',col4:31},
    {col1:'Bhushan', col2:'Patil', col3:'Nashik',col4:26},
    {col1:'Vaibhav', col2:'Durhaya', col3:'Bhopal',col4:32},
    {col1:'Richa', col2:'Saxena', col3:'Lucknow',col4:30},
    {col1:'Ajay', col2:'Gupta', col3:'Allahabad',col4:33},
    {col1:'Tushar', col2:'Bobade', col3:'Mumbai',col4:28},
    {col1:'Limbaji', col2:'Rathod', col3:'Rajasthan',col4:30},
    {col1:'Sonali', col2:'Katkar', col3:'Mumbai',col4:26},
    {col1:'Kiran', col2:'Yadav', col3:'Nashik',col4:31},
    {col1:'Bhushan', col2:'Patil', col3:'Nashik',col4:26},
    {col1:'Vaibhav', col2:'Durhaya', col3:'Bhopal',col4:32},
    {col1:'Richa', col2:'Saxena', col3:'Lucknow',col4:30},
    {col1:'Ajay', col2:'Gupta', col3:'Allahabad',col4:33},
    {col1:'Tushar', col2:'Bobade', col3:'Mumbai',col4:28},
    {col1:'Limbaji', col2:'Rathod', col3:'Rajasthan',col4:30},
    {col1:'Sonali', col2:'Katkar', col3:'Mumbai',col4:26},
    {col1:'Kiran', col2:'Yadav', col3:'Nashik',col4:31},
    {col1:'Bhushan', col2:'Patil', col3:'Nashik',col4:26}
  ];

  rows2 = [
    {col1:'Vaibhav', col2:'Durhaya', col3:'Bhopal',col4:32},
    {col1:'Richa', col2:'Saxena', col3:'Lucknow',col4:30},
    {col1:'Ajay', col2:'Gupta', col3:'Allahabad',col4:33},
    {col1:'Tushar', col2:'Bobade', col3:'Mumbai',col4:28}
  ];

  ChangeData() {
    // this.rows = [
    //   {col1:'V', col2:'Durhaya', col3:'Bhopal',col4:32,col5:"1984/05/04"},
    //   {col1:'R', col2:'Saxena', col3:'Lucknow',col4:30,col5:"1984/05/05"},
    //   {col1:'A', col2:'Gupta', col3:'Allahabad',col4:33,col5:"1984/05/06"},
    //   {col1:'T', col2:'Bobade', col3:'Mumbai',col4:28,col5:"1984/05/07"},
    //   {col1:'L', col2:'Rathod', col3:'Rajasthan',col4:30,col5:"1984/05/08"},
    //   {col1:'S', col2:'Katkar', col3:'Mumbai',col4:26,col5:"1984/05/09"},
    //   {col1:'K', col2:'Yadav', col3:'Nashik',col4:31,col5:"1984/05/10"},
    //   {col1:'B', col2:'Patil', col3:'Nashik',col4:26,col5:"1984/05/11"}
    // ];
    //this.pageSize = 5;
    this.updateCheckBox = {property:'col1',propertyValue:'Vaibhav',IsChecked:true};
  }
}
